import enum


class TitleCaseEnum(enum.Enum):
    def __str__(self):
        # Replace underscores with spaces and convert to title case
        return self.value.replace('_', ' ').title()


class PeriodTypes(TitleCaseEnum):
    BEFORE_SCHOOL = "BEFORE_SCHOOL"
    FIRST_PERIOD_TRANSITION = "FIRST_PERIOD_TRANSITION"
    FIRST_PERIOD = "FIRST_PERIOD"
    SECOND_PERIOD_TRANSITION = "SECOND_PERIOD_TRANSITION"
    SECOND_PERIOD = "SECOND_PERIOD"
    THIRD_PERIOD_TRANSITION = "THIRD_PERIOD_TRANSITION"
    THIRD_PERIOD = "THIRD_PERIOD"
    FOURTH_PERIOD_TRANSITION = "FOURTH_PERIOD_TRANSITION"
    FOURTH_PERIOD = "FOURTH_PERIOD"
    STINGER_FIRST_HALF_TRANSITION = "STINGER_FIRST_HALF_TRANSITION"
    STINGER_FIRST_HALF = "STINGER_FIRST_HALF"
    STINGER_SECOND_HALF_TRANSITION = "STINGER_SECOND_HALF_TRANSITION"
    STINGER_SECOND_HALF = "STINGER_SECOND_HALF"
    FIFTH_PERIOD_TRANSITION = "FIFTH_PERIOD_TRANSITION"
    FIFTH_PERIOD = "FIFTH_PERIOD"
    SIXTH_PERIOD_TRANSITION = "SIXTH_PERIOD_TRANSITION"
    SIXTH_PERIOD = "SIXTH_PERIOD"
    SEVENTH_PERIOD_TRANSITION = "SEVENTH_PERIOD_TRANSITION"
    SEVENTH_PERIOD = "SEVENTH_PERIOD"
    EIGHTH_PERIOD_TRANSITION = "EIGHTH_PERIOD_TRANSITION"
    EIGHTH_PERIOD = "EIGHTH_PERIOD"
    AFTER_SCHOOL = "AFTER_SCHOOL"
