name: Restart API

on: [push]

jobs:
    Error-Check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Python Environment Setup
              uses: actions/setup-python@v2
              with:
                python-version: '3.x'
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install pylint
            - name: Lint Files
              run: |
                  # Lint all Python files
                  pylint --disable=C,R . --recursive=true

    Restart-API:
        runs-on: ubuntu-latest
        needs: [Error-Check]
        steps:
            - name: Call API
              run: |
                  curl -X POST https://api.soos.dev/restart -H "Authorization: Bearer ${{ secrets.API_KEY }}"
